# Generated by Django 3.2.4 on 2021-06-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
