# Generated by Django 3.2.4 on 2021-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAS', '0002_alter_history_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='percentage',
            new_name='Confidence',
        ),
    ]
